config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root to: 'pages#home'

  get '/businesses', to: 'categories#show'

  resources :categories, only: [:index]
  resources :businesses, only: [:index]

  resources :categories, only: [:show] do
    resources :businesses, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'businesses'
    end
  end

  resources :businesses do
    member do
      get 'book'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord

  geocoded_by :location

  mount_uploader :photo, PhotoUploader

  belongs_to :owner, class_name: 'User'
  belongs_to :category

  has_many :settlements
  has_many :users, through: :settlements

  validates :owner_id, :title, :budget, :location, :category, presence: true
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :businesses

  validates :name, presence: true, inclusion: { in: %w[Bakers Caligraphes Caterers Dress Florists Hair Photographers Venues] }
  # validates :name, uniqueness: true
end

app/models/settlement.rb
class Settlement < ApplicationRecord
  belongs_to :user
  belongs_to :business
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :photo, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:google]

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end

  validates :username, presence: true, uniqueness: true

  has_many :o_businesses, foreign_key: :owner_id, class_name: 'Business'

  has_many :settlements
  has_many :businesses, through: :settlements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    true
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :home]
  before_action :find_business, only: [:show, :edit, :update, :destroy, :book]
  before_action :find_category, only: [:index]

  def index
    @businesses = Business.where(category: @category)
  end

  def show
    authorize @business

    # @business = Business.where.not(latitude: nil, longitude: nil)

    @markers = [{
      lng: @business.longitude,
      lat: @business.latitude
      # infoWindow: render_to_string(partial: "infowindow", locals: { business: @business })
    }]

    @business
  end

  def new
    # @category = Category.find[:category_id]
    @business = Business.new
  end

  def edit
    authorize @business
  end

  def create
    @category = Category.find(business_params[:category_id])
    @business = Business.new(business_params)
    authorize @business
    @business.owner = current_user

    if @business.save
      redirect_to business_path(@business), notice: 'You are in the market!'
    else
      flash[:alert] = 'Something went wrong. Please review your errors'
      render :new
    end
  end

  def update
    authorize @business
    if @business.update(business_params)
      redirect_to business_path(@business), notice: "#{@business.name} info updated."
    else
      flash[:alert] = 'Something went wrong. Please review your errors'
      render :edit
    end
  end

  def destroy
    authorize @business
    @business.destroy
    redirect_to businesses_path
  end

  def book
    @settlement = Settlement.new
    @settlement.user = current_user
    @settlement.business = @business
    if @settlement.save
      flash[:notice] = "You have this item"
      redirect_to business_path(@business)
    else
      flash[:alert] = "Sorry!"
      redirect_to business_path(@business)
    end
  end

  private

  def business_params
    params.require(:business).permit(:title, :budget, :rating, :location, :photo, :calendar, :category_id)
  end

  def find_business
    @business = Business.find(params[:id])
  end

  def find_category
    @category = Category.find(params[:category_id])
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def digitalocean
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    # @user = current_user
  end

  def show
  #   @category = Category.find(params[:id])
  #   @businesses = Business.where(category: @category)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    if user_signed_in?
      redirect_to '/categories#index'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :businesses]
  before_action :authorize_user, only: [:edit, :show, :update, :businesses]

  def show
    @o_businesses = Business.where(owner: @user)
    @businesses = Settlement.where(user: @user)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User is successfully updated.'
    else
      render :edit
    end
  end

  def businesses
    @owned_businesses = Business.where(owner: @user)
    @businesses = Settlement.where(user: @user).map { |b| b.business }
  end

  private

  def authorize_user
    authorize @user
  end

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:photo, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/businesses/_cards.html.erb
<div class="col-xs-3">
  <div class="business-cards">
    <div class="business-photo">
      <% if business.photo.present? %>
        <div class="business-image business-loaded" style="background-image: url(<%= cl_image_path business.photo %>); background-size: cover">
        </div>
      <% else %>
        <div class="business-image">
          <%= image_tag asset_path('logo_moh.png') %>
        </div>
      <% end %>
    </div>
    <div class="business-bottom">
      <div class="user-photo">
        <% if business.owner.photo.present? %>
          <div class="user-image avatar" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path business.owner.photo %>); ; background-size: cover">
          </div>
        <% else %>
          <div class="user-image avatar">
            <%= image_tag asset_path('bride_profile.jpg') %>
          </div>
        <% end %>
      </div>
      <div class="business-info">
        <p><%= business.title %></p>
        <p><%= business.location %></p>
        <% if business.budget < 20000 %>
          <p>$</p>
        <% elsif business.budget >= 20000 && business.budget <= 50000 %>
          <p>$$</p>
        <% else %>
          <p>$$$</p>
        <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/businesses/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h3>Update Your Business</h3>
      <%= simple_form_for(business) do |t| %>
        <div class="row">
          <div class="col-xs-12">
            <%= t.input :title %>
            <%= t.input :budget %>
            <%= t.input :rating %>
            <%= t.input :calendar %>
            <%= t.input :location, id: "location" %>

            <div>
              <%= t.select :category, Business::CATEGORIES %>
            </div>

            <%= t.input :max_participants %>
            <%= t.input :photo %>
            <%= t.input :photo_cache, as: :hidden %>
            <div class="form-actions">
              <%= t.button :submit, "Update" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to "Back", :back %>

app/views/businesses/index.html.erb
<div class="container">
  <div class="card-container">
    <div class="row">
      <div class="cards">
        <h2><%= @category.name %></h2>
        <% @businesses.each do |business| %>
          <%= link_to business_path(business) do %>
            <%= render 'cards', business: business %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/businesses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h3>Do you have a business?</h3>
      <%= simple_form_for @business do |t| %>
        <div class="row">
          <div class="col-xs-12">
            <%= t.input :title %>
            <%= t.input :budget %>
            <%= t.input :rating %>
            <%= t.input :calendar %>
            <%= t.input :location, id: "location" %>

            <div>
              <%= t.association :category, collection: Category.all %>
            </div>

            <%= t.input :photo %>
            <%= t.input :photo_cache, as: :hidden %>
            <div class="form-actions">
              <%= t.button :submit %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to "Back", :back %>

app/views/businesses/show.html.erb
<p><%= @business.title %></p>

<div
    id="map"
    style="width: 100%;
    height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>

app/views/categories/_card.html.erb
<div class="col-xs-3">
  <div class="category-card">
    <div class="category-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2))">
      <%= image_tag(category.name) %>
    </div>
    <div class="category-name">
        <%= category.name %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="card-container">
    <div class="row">
      <div class="cards">
        <% @categories.each do |category| %>
          <%= link_to category_businesses_path(category) do %>
            <%= render 'card', category: category %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MOH</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%#= javascript_link_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<% if !user_signed_in? %>
  <body style="background-color: #3BA5A5">
    <div class="container">
      <div class="home-page">
        <div class="not-signed">
          <div class="big-logo">
            <%= image_tag asset_path('logo_moh.png'), class: "style-unsigned" %>
          </div>
          <div class="sign-up">
            <h1>Maid of Honor</h1>
            <h4>Your Personal Wedding Assistant!</h4>
            <p>Don't have an account yet? <%= link_to "Sign Up", new_user_registration_path %></p>
          </div>
        </div>
      </div>
    </div>
  </body>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-moh">
  <% if user_signed_in? %>
    <% if current_user %>
      <div class="nav-moh-left hidden-xs hidden-sm">
        <div class="navbar-moh-item-left">
          <div class="dropdown">
            <%= image_tag asset_path('logo_moh.png'), alt: "alttext", class: "moh-logo dropdown-toggle", id: "navbar-moh-menu", "data-toggle": "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-left navbar-moh-dropdown-menu-left">
              <!-- home path -->
              <li>
                <%= link_to root_path do %>
                  Home
                <% end %>
              </li>

              <!-- Categories -->
              <% Category.all.each do |category| %>
                <li><%= link_to category_businesses_path(category) do %>
                    <% category.name %>
                  <% end %>
                </li>
              <% end %>

              <!-- My Calendar -->
              <li><a href="#">My Calendar</a></li>
              <!-- My Lists -->
              <li><a href="#">My Lists</a></li>
              <li><a href="#">About</a></li>
              <!-- Contact -->
              <li><a href="#">Contact</a></li>
              <!-- Logout -->
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="nav-moh-right hidden-xs hidden-sm">
        <%= link_to "Owning a business?", new_business_path, class: "navbar-moh-item-right navbar-moh-link" %>
        <div class="navbar-moh-item-right">
          <div class="dropdown">
            <% if current_user.photo.present? %>
              <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-moh-menu", "data-toggle" => "dropdown" %>
              <ul class="dropdown-menu dropdown-menu-right navbar-moh-dropdown-menu">
            <% else %>
               <%= image_tag asset_path("bride_profile.jpg"), alt: "alttext", class: "avatar dropdown-toggle", id: "navbar-moh-menu", "data-toggle": "dropdown" %>
               <ul class="dropdown-menu dropdown-menu-right navbar-moh-dropdown-menu">
            <% end %>
              <li>
                <%= link_to user_path(current_user) do %>
                  <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                    <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="nav-moh-left hidden-xs hidden-sm">
      <div class="navbar-moh-item">
        <div class="dropdown">
          <%#= image_tag asset_path('logo_moh.png'), alt: "alttext", class: "moh-logo dropdown-toggle", id: "navbar-moh-menu", "data-toggle": "dropdown" %>

            <!-- home path -->
        </div>
      </div>
    </div>
    <div class="nav-moh-right hidden-xs hidden-sm">
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-moh-item navbar-moh-link" %>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<h2>Edit your profile</h2>

<%= simple_form_for(user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, required: true, autofocus: true %>

    <%= f.input :username %>
    <%= f.input :description %>

    <%= f.input :current_password,
                hint: "we need your current password to confirm your changes",
                required: true,
                input_html: { autocomplete: "current-password" } %>
    <%= f.input :password,
                hint: "leave it blank if you don't want to change it",
                required: false,
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :password_confirmation,
                required: false,
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update" %>
  </div>
<% end %>


<%= link_to "Back", :back %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>